/**
 * FindLink — shared SEO primitives.
 *
 * Single source of truth for the site identity used by metadata, canonical
 * URLs, Open Graph / Twitter cards and JSON-LD structured data.
 *
 * Server-side only (imported from server components / route files — never
 * from client components). All URLs are ABSOLUTE (schema.org requirement;
 * Google also requires absolute URLs in sitemaps and structured data).
 */

const rawUrl = process.env.APP_URL || "https://findlink.site"

/** Canonical site origin, no trailing slash — e.g. https://findlink.site */
export const SITE_URL = rawUrl.replace(/\/+$/, "")

export const SITE_NAME = "FindLink"

export const SITE_TAGLINE = "Find, share & shorten links"

/** Homepage <title> — 46 chars: primary keywords + Free + brand last (never truncates in SERPs). */
export const HOME_TITLE =
  "Free Link Directory & URL Shortener | FindLink"

export const SITE_DESCRIPTION =
  "Free community directory & URL shortener. Discover Telegram, WhatsApp & Facebook groups by country & language. Shorten URLs with click analytics."

/** Default social card (1200x630, generated by scripts/generate-og-image.mjs). */
export const OG_IMAGE_PATH = "/og-image.png"

/** Turn a site-relative path into an absolute URL. */
export function absoluteUrl(path: string): string {
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`
}

/* ------------------------------------------------------------------ */
/* JSON-LD builders (schema.org, ACTIVE types only — validated against */
/* the Agentic-SEO-Skill reference: no deprecated/restricted types).    */
/* ------------------------------------------------------------------ */

export interface BreadcrumbItem {
  name: string
  url: string // absolute
}

/** WebSite + SearchAction — makes the /explore?q= search box eligible as a sitelinks search box. */
export function websiteSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": absoluteUrl("/#website"),
    name: SITE_NAME,
    alternateName: "findlink.site",
    url: SITE_URL,
    description: SITE_DESCRIPTION,
    publisher: { "@id": absoluteUrl("/#organization") },
    potentialAction: {
      "@type": "SearchAction",
      target: {
        "@type": "EntryPoint",
        urlTemplate: `${SITE_URL}/explore?q={search_term_string}`,
      },
      "query-input": "required name=search_term_string",
    },
  }
}

/** Organization — brand entity for the site. */
export function organizationSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": absoluteUrl("/#organization"),
    name: SITE_NAME,
    url: SITE_URL,
    logo: {
      "@type": "ImageObject",
      url: absoluteUrl("/logo.svg"),
    },
    description: SITE_DESCRIPTION,
  }
}

/** BreadcrumbList — mirrors the visible breadcrumb navigation. */
export function breadcrumbSchema(items: BreadcrumbItem[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: item.url,
    })),
  }
}

export interface CollectionItem {
  name: string
  url: string // absolute
}

/** CollectionPage + embedded ItemList — for directory listing pages. */
export function collectionSchema(opts: {
  name: string
  description: string
  url: string // absolute
  items: CollectionItem[]
}) {
  return {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    name: opts.name,
    description: opts.description,
    url: opts.url,
    isPartOf: { "@id": absoluteUrl("/#website") },
    ...(opts.items.length > 0
      ? {
          mainEntity: {
            "@type": "ItemList",
            numberOfItems: opts.items.length,
            itemListElement: opts.items.map((item, i) => ({
              "@type": "ListItem",
              position: i + 1,
              name: item.name,
              url: item.url,
            })),
          },
        }
      : {}),
  }
}

/** Product + Offer — FindLink Premium ($3 / 30 days, PayPal). Truthful values only. */
export function premiumProductSchema(opts: { price: string; days: number }) {
  return {
    "@context": "https://schema.org",
    "@type": "Product",
    name: "FindLink Premium",
    description: `Unlimited tracked short links with full click analytics — country, device, browser and referrer — on every link. ${opts.days} days of premium per payment.`,
    url: absoluteUrl("/premium"),
    image: absoluteUrl(OG_IMAGE_PATH),
    brand: { "@type": "Brand", name: SITE_NAME },
    offers: {
      "@type": "Offer",
      url: absoluteUrl("/premium"),
      price: opts.price,
      priceCurrency: "USD",
      availability: "https://schema.org/InStock",
    },
  }
}

/**
 * WebPage + CreativeWork (mainEntity) — for an individual public listing page
 * (/link/[slug]). Describes the page itself and the community listing it
 * presents; values come straight from the submitted listing (truthful only —
 * no fabricated ratings or counts).
 */
export function listingSchema(opts: {
  name: string
  description: string
  url: string // absolute
  category: string
  datePublished?: Date
  inLanguage?: string
}) {
  return {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "@id": `${opts.url}#webpage`,
    url: opts.url,
    name: opts.name,
    description: opts.description,
    isPartOf: { "@id": absoluteUrl("/#website") },
    mainEntity: {
      "@type": "CreativeWork",
      name: opts.name,
      description: opts.description,
      url: opts.url,
      genre: opts.category,
      ...(opts.datePublished ? { datePublished: opts.datePublished.toISOString() } : {}),
      ...(opts.inLanguage ? { inLanguage: opts.inLanguage } : {}),
    },
  }
}
